#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBE793007AD22DF7E (tsujan2000@gmail.com)
#
Name     : qtxdg-tools
Version  : 3.9.1
Release  : 1
URL      : https://github.com/lxqt/qtxdg-tools/releases/download/3.9.1/qtxdg-tools-3.9.1.tar.xz
Source0  : https://github.com/lxqt/qtxdg-tools/releases/download/3.9.1/qtxdg-tools-3.9.1.tar.xz
Source1  : https://github.com/lxqt/qtxdg-tools/releases/download/3.9.1/qtxdg-tools-3.9.1.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: qtxdg-tools-bin = %{version}-%{release}
Requires: qtxdg-tools-data = %{version}-%{release}
Requires: qtxdg-tools-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-gnome
BuildRequires : buildreq-kde
BuildRequires : liblxqt-dev
BuildRequires : lxqt-build-tools
BuildRequires : qtbase-dev mesa-dev

%description
# qtxdg-tools
## Overview
User tools for [libqtxdg](https://github.com/lxqt/libqtxdg).

%package bin
Summary: bin components for the qtxdg-tools package.
Group: Binaries
Requires: qtxdg-tools-data = %{version}-%{release}
Requires: qtxdg-tools-license = %{version}-%{release}

%description bin
bin components for the qtxdg-tools package.


%package data
Summary: data components for the qtxdg-tools package.
Group: Data

%description data
data components for the qtxdg-tools package.


%package license
Summary: license components for the qtxdg-tools package.
Group: Default

%description license
license components for the qtxdg-tools package.


%prep
%setup -q -n qtxdg-tools-3.9.1
cd %{_builddir}/qtxdg-tools-3.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1652280555
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1652280555
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qtxdg-tools
cp %{_builddir}/qtxdg-tools-3.9.1/LICENSE %{buildroot}/usr/share/package-licenses/qtxdg-tools/01a6b4bf79aca9b556822601186afab86e8c4fbf
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qtxdg-mat

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qtxdg-tools/01a6b4bf79aca9b556822601186afab86e8c4fbf
